chore(deps-dev): bump lint-staged from 13.3.0 to 15.5.0
Bumps [lint-staged](https://github.com/lint-staged/lint-staged) from 13.3.0 to 15.5.0.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/lint-staged/lint-staged/releases">lint-staged's releases</a>.</em></p>
<blockquote>
<h2>v15.5.0</h2>
<h3>Minor Changes</h3>
<ul>
<li>
<p><a href="https://redirect.github.com/lint-staged/lint-staged/pull/1526">#1526</a> <a href="https://github.com/lint-staged/lint-staged/commit/630af5fb48ed43eb6ccaefa7a9d9612309023b6f"><code>630af5f</code></a> Thanks <a href="https://github.com/iiroj"><code>@​iiroj</code></a>! - Lint-staged no longer resets to the original state when preventing an empty git commit. This happens when your configured tasks reset all the staged changes, typically when trying to commit formatting changes which conflict with your linter setup like ESLint or Prettier.</p>
<h3>Example with Prettier</h3>
<p>By default Prettier <a href="https://prettier.io/docs/rationale#strings">prefers double quotes</a>.</p>
<h4>Previously</h4>
<ol>
<li>Stage <code>file.js</code> with only double quotes <code>&quot;</code> changed to <code>'</code></li>
<li>Run <code>git commit -am &quot;I don't like double quotes&quot;</code></li>
<li><em>Lint-staged</em> runs <code>prettier --write file.js</code>, converting all the <code>'</code> back to <code>&quot;</code></li>
<li>Because there are now no changes, <em>lint-staged</em> fails, cancels the commit, and resets back to the original state</li>
<li>Commit was not done, original state is restored and single quotes <code>'</code> are staged</li>
</ol>
<h4>Now</h4>
<ol>
<li>Stage <code>file.js</code> with only double-quotes <code>&quot;</code> changed to <code>'</code></li>
<li>Run <code>git commit -am &quot;I don't like double quotes&quot;</code></li>
<li><em>Lint-staged</em> runs <code>prettier --write file.js</code>, converting all the <code>'</code> back to <code>&quot;</code></li>
<li>Because there are now no changes, <em>lint-staged</em> fails and cancels the commit</li>
<li>Commit was not done, and there are no staged changes</li>
</ol>
</li>
</ul>
<h2>v15.4.3</h2>
<h3>Patch Changes</h3>
<ul>
<li><a href="https://redirect.github.com/lint-staged/lint-staged/pull/1512">#1512</a> <a href="https://github.com/lint-staged/lint-staged/commit/cbfed1dfd2465c4198c692955281f0836600bea1"><code>cbfed1d</code></a> Thanks <a href="https://github.com/tarik02"><code>@​tarik02</code></a>! - Adjust TypeScript types for the default export so that it can be used as a value without error TS2693.</li>
</ul>
<h2>v15.4.2</h2>
<h3>Patch Changes</h3>
<ul>
<li><a href="https://redirect.github.com/lint-staged/lint-staged/pull/1509">#1509</a> <a href="https://github.com/lint-staged/lint-staged/commit/8827ebf29dc8f25149a36450b4a0023425202e18"><code>8827ebf</code></a> Thanks <a href="https://github.com/iiroj"><code>@​iiroj</code></a>! - Change <em>lint-staged</em>'s dependencies to use <a href="https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004">caret (<code>^</code>) ranges</a> instead of <a href="https://docs.npmjs.com/cli/v6/using-npm/semver#tilde-ranges-123-12-1">tilde (<code>~</code>)</a>. This makes it easier for package managers to perform dependency management when minor-level updates are also permitted instead of just patch-level.</li>
</ul>
<h2>v15.4.1</h2>
<h3>Patch Changes</h3>
<ul>
<li>
<p><a href="https://redirect.github.com/lint-staged/lint-staged/pull/1504">#1504</a> <a href="https://github.com/lint-staged/lint-staged/commit/1c7a45ed2c7fee9d5f55337be16a51e4c9b240e1"><code>1c7a45e</code></a> Thanks <a href="https://github.com/iiroj"><code>@​iiroj</code></a>! - Default TypeScript config filenames match JS equivalents.</p>
</li>
<li>
<p><a href="https://redirect.github.com/lint-staged/lint-staged/pull/1504">#1504</a> <a href="https://github.com/lint-staged/lint-staged/commit/9cc18c9debb185490f9ae4f9c1d21ec8c2587393"><code>9cc18c9</code></a> Thanks <a href="https://github.com/iiroj"><code>@​iiroj</code></a>! - Add missing conditional exports syntax for TypeScript types.</p>
</li>
</ul>
<h2>v15.4.0</h2>
<h3>Minor Changes</h3>
<ul>
<li>
<p><a href="https://redirect.github.com/lint-staged/lint-staged/pull/1500">#1500</a> <a href="https://github.com/lint-staged/lint-staged/commit/a8ec1ddb587d2c1c2420dbb4baff8160f0ac46c9"><code>a8ec1dd</code></a> Thanks <a href="https://github.com/iiroj"><code>@​iiroj</code></a>! - <em>Lint-staged</em> now provides TypeScript types for the configuration and main Node.js API. You can use the JSDoc syntax in your JS configuration files:</p>
<pre lang="js"><code>/**
 * @filename: lint-staged.config.js
</code></pre>
</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/lint-staged/lint-staged/blob/main/CHANGELOG.md">lint-staged's changelog</a>.</em></p>
<blockquote>
<h2>15.5.0</h2>
<h3>Minor Changes</h3>
<ul>
<li>
<p><a href="https://redirect.github.com/lint-staged/lint-staged/pull/1526">#1526</a> <a href="https://github.com/lint-staged/lint-staged/commit/630af5fb48ed43eb6ccaefa7a9d9612309023b6f"><code>630af5f</code></a> Thanks <a href="https://github.com/iiroj"><code>@​iiroj</code></a>! - Lint-staged no longer resets to the original state when preventing an empty git commit. This happens when your configured tasks reset all the staged changes, typically when trying to commit formatting changes which conflict with your linter setup like ESLint or Prettier.</p>
<h3>Example with Prettier</h3>
<p>By default Prettier <a href="https://prettier.io/docs/rationale#strings">prefers double quotes</a>.</p>
<h4>Previously</h4>
<ol>
<li>Stage <code>file.js</code> with only double quotes <code>&quot;</code> changed to <code>'</code></li>
<li>Run <code>git commit -am &quot;I don't like double quotes&quot;</code></li>
<li><em>Lint-staged</em> runs <code>prettier --write file.js</code>, converting all the <code>'</code> back to <code>&quot;</code></li>
<li>Because there are now no changes, <em>lint-staged</em> fails, cancels the commit, and resets back to the original state</li>
<li>Commit was not done, original state is restored and single quotes <code>'</code> are staged</li>
</ol>
<h4>Now</h4>
<ol>
<li>Stage <code>file.js</code> with only double-quotes <code>&quot;</code> changed to <code>'</code></li>
<li>Run <code>git commit -am &quot;I don't like double quotes&quot;</code></li>
<li><em>Lint-staged</em> runs <code>prettier --write file.js</code>, converting all the <code>'</code> back to <code>&quot;</code></li>
<li>Because there are now no changes, <em>lint-staged</em> fails and cancels the commit</li>
<li>Commit was not done, and there are no staged changes</li>
</ol>
</li>
</ul>
<h2>15.4.3</h2>
<h3>Patch Changes</h3>
<ul>
<li><a href="https://redirect.github.com/lint-staged/lint-staged/pull/1512">#1512</a> <a href="https://github.com/lint-staged/lint-staged/commit/cbfed1dfd2465c4198c692955281f0836600bea1"><code>cbfed1d</code></a> Thanks <a href="https://github.com/tarik02"><code>@​tarik02</code></a>! - Adjust TypeScript types for the default export so that it can be used as a value without error TS2693.</li>
</ul>
<h2>15.4.2</h2>
<h3>Patch Changes</h3>
<ul>
<li><a href="https://redirect.github.com/lint-staged/lint-staged/pull/1509">#1509</a> <a href="https://github.com/lint-staged/lint-staged/commit/8827ebf29dc8f25149a36450b4a0023425202e18"><code>8827ebf</code></a> Thanks <a href="https://github.com/iiroj"><code>@​iiroj</code></a>! - Change <em>lint-staged</em>'s dependencies to use <a href="https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004">caret (<code>^</code>) ranges</a> instead of <a href="https://docs.npmjs.com/cli/v6/using-npm/semver#tilde-ranges-123-12-1">tilde (<code>~</code>)</a>. This makes it easier for package managers to perform dependency management when minor-level updates are also permitted instead of just patch-level.</li>
</ul>
<h2>15.4.1</h2>
<h3>Patch Changes</h3>
<ul>
<li>
<p><a href="https://redirect.github.com/lint-staged/lint-staged/pull/1504">#1504</a> <a href="https://github.com/lint-staged/lint-staged/commit/1c7a45ed2c7fee9d5f55337be16a51e4c9b240e1"><code>1c7a45e</code></a> Thanks <a href="https://github.com/iiroj"><code>@​iiroj</code></a>! - Default TypeScript config filenames match JS equivalents.</p>
</li>
<li>
<p><a href="https://redirect.github.com/lint-staged/lint-staged/pull/1504">#1504</a> <a href="https://github.com/lint-staged/lint-staged/commit/9cc18c9debb185490f9ae4f9c1d21ec8c2587393"><code>9cc18c9</code></a> Thanks <a href="https://github.com/iiroj"><code>@​iiroj</code></a>! - Add missing conditional exports syntax for TypeScript types.</p>
</li>
</ul>
<h2>15.4.0</h2>
<h3>Minor Changes</h3>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/lint-staged/lint-staged/commit/7e6abe47c2c7584e72ded13a16d2e93d0a98f57b"><code>7e6abe4</code></a> chore(changeset): release</li>
<li><a href="https://github.com/lint-staged/lint-staged/commit/0ebfa69f49a8c3335a07bb6a170b5700776ef52d"><code>0ebfa69</code></a> build(deps): update dependencies</li>
<li><a href="https://github.com/lint-staged/lint-staged/commit/630af5fb48ed43eb6ccaefa7a9d9612309023b6f"><code>630af5f</code></a> feat: do not reset to original state when preventing empty commit</li>
<li><a href="https://github.com/lint-staged/lint-staged/commit/7b8be705e29c9ec91964d0b12e6c732789a00476"><code>7b8be70</code></a> chore: update default branch references from &quot;master&quot; to &quot;main&quot;</li>
<li><a href="https://github.com/lint-staged/lint-staged/commit/362a78df9ccb0fe8515c42164f93adaa87469954"><code>362a78d</code></a> docs: add workaround for tsc ignoring tsconfig.json issue to README FAQ (<a href="https://redirect.github.com/lint-staged/lint-staged/issues/1523">#1523</a>)</li>
<li><a href="https://github.com/lint-staged/lint-staged/commit/e013823e1867f076eb35e886c0422060dccb23b9"><code>e013823</code></a> fix: &quot;node_modules&quot; typo in eslint.config.js</li>
<li><a href="https://github.com/lint-staged/lint-staged/commit/67019ee77fac5e116ce86816663d8d1ee7e5a37a"><code>67019ee</code></a> test: add integration test to ensure unmodified merged files are not linted (...</li>
<li><a href="https://github.com/lint-staged/lint-staged/commit/366f8bdf90dbd18e9547b69d6b7d16f82bf4e8c2"><code>366f8bd</code></a> refactor: move TypeScript types to &quot;index.d.ts&quot; file</li>
<li><a href="https://github.com/lint-staged/lint-staged/commit/85ea6a40a7902f1c4b16e43e07b3adca196bbe9f"><code>85ea6a4</code></a> docs: adjust readme regarding monorepo setup</li>
<li><a href="https://github.com/lint-staged/lint-staged/commit/e53f950dd74255226f8ecdcfe0aa0a9ebd820277"><code>e53f950</code></a> chore(changeset): release</li>
<li>Additional commits viewable in <a href="https://github.com/lint-staged/lint-staged/compare/v13.3.0...v15.5.0">compare view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=lint-staged&package-manager=npm_and_yarn&previous-version=13.3.0&new-version=15.5.0)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

You can trigger a rebase of this PR by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)


</details>

> **Note**
> Automatic rebases have been disabled on this pull request as it has been open for over 30 days.